CREATE TABLE COMPANY (
    COD_COMPANY NUMBER(4),
    COMPANY_NAME VARCHAR2(20) NOT NULL,
    CP NUMBER(5) NOT NULL,
    CONSTRAINT PK_COMPANY PRIMARY KEY(COD_COMPANY)
);

CREATE TABLE PLACES (
    REGION VARCHAR(20),
    COUNTRY VARCHAR2(20) NOT NULL,
    ENTRY_DATE DATE,
    EXIT_DATE DATE,
    ODOMETER_VALUE NUMBER(7) NOT NULL,
    CONSTRAINT PK_PLACES PRIMARY KEY(REGION)
);

CREATE TABLE DRIVER (
    DNI NUMBER(8),
    DRIVER_NAME VARCHAR2(20) NOT NULL,
    FIRST_SURNAME VARCHAR2(15) NOT NULL,
    LAST_SURNAME VARCHAR2(15),
    PREFERRED_IDIOME VARCHAR2(2) NOT NULL,
    DISCHARGE_DATE DATE NOT NULL,
    PLACES_REGION VARCHAR2(20),
    CONSTRAINT PK_DRIVER PRIMARY KEY(DNI),
    CONSTRAINT FK_DRIVER_PLACES FOREIGN KEY(PLACES_REGION) REFERENCES PLACES (REGION)
);

CREATE TABLE DRIVER_WORK (
    COD_COMPANY NUMBER(4),
    DRIVER_DNI NUMBER(8),
    WORK_START_DATE DATE,
    WORK_FINISH_DATE DATE NOT NULL,
    CONSTRAINT PK_DRIVER_WORK PRIMARY KEY(COD_COMPANY,DNI,WORK_START_DATE),
    CONSTRAINT FK_DRIVERWORK_COMPANY FOREIGN KEY(COD_COMPANY) REFERENCES COMPANY(COD_COMPANY),
    CONSTRAINT FK_DRIVERWORK_DRIVER FOREIGN KEY(DRIVER_DNI) REFERENCES DRIVER(DNI)
);

CREATE TABLE VEHICLE (
    VEHICLE_REGISTER_NUM NUMBER(5),
    VEHICLE_NATION_REGISTER VARCHAR(20),
    COMPANY_COD NUMBER(4),
    CONSTRAINT PK_VEHICLE PRIMARY KEY(VEHICLE_REGISTER_NUM),
    CONSTRAINT FK_VEHICLE_COMPANY FOREIGN KEY(COMPANY_COD) REFERENCES COMPANY (COMPANY_COD)
);

CREATE TABLE VEHICLE_USED (
    FIRST_USE_DATE DATE,
    LAST_USE_DATE DATE NOT NULL,
    ODOMETER_START NUMBER(8) NOT NULL,
    ODOMETER_FINISH NUMBER(8) NOT NULL,
    VEHICLE_REGISTER_NUM NUMBER(5) NOT NULL,
    DRIVER_DNI NUMBER(8),
    CONSTRAINT PK_VEHICLE_USED PRIMARY KEY (FIRST_USE_DATE),
    CONSTRAINT FK_VEHICLEUSED_VEHICLE FOREIGN KEY(VEHICLE_REGISTER_NUM) REFERENCES VEHICLE (VEHICLE_REGISTER_NUM),
    CONSTRAINT FK_VEHICLEUSED_DIVER FOREIGN KEY(DRIVER_DNI) REFERENCES DRIVER (DNI)
);

CREATE TABLE CARD (
    CARD_ID NUMBER(8),
    EXPIRATION_DATE DATE,
    ACQUISITION_DATE DATE,
    DRIVER_DNI NUMBER(8),
    CONSTRAINT PK_CARD PRIMARY KEY(CARD_ID),
    CONSTRAINT FK_CARD_DRIVER FOREIGN KEY(DRIVER_DNI) REFERENCES DRIVER (DNI)
);

CREATE TABLE ACTIVITY (
    A_ID NUMBER(5),
    ACTIVITY VARCHAR2(15),
    STATUS VARCHAR2(20),
    REGIME VARCHAR2(20),
    DRIVER VARCHAR2(20),
    TIME DATE,
    COMPANY_COD NUMBER(4),
    DRIVER_DNI NUMBER(8),
    CONSTRAINT PK_ACTIVITY PRIMARY KEY(A_ID),
    CONSTRAINT FK_ACTIVITY_COMPANY FOREIGN KEY(COMPANY_COD) REFERENCES ACTIVITY(COMPANY_COD),
    CONSTRAINT FK_ACTIVITY_DRIVER FOREIGN KEY(DRIVER_DNI) REFERENCES DRIVER(DRIVER_DNI)
); 