CREATE TABLE ACTIVITY (
    A_ID NUMBER(5),
    ACTIVITY VARCHAR2(15),
    STATUS VARCHAR2(20),
    REGIME VARCHAR2(20),
    DRIVER VARCHAR2(20),
    TIME DATE,
    COMPANY_COD NUMBER(4),
    DRIVER_DNI NUMBER(8),
    CONSTRAINT PK_ACTIVITY PRIMARY KEY(A_ID),
    CONSTRAINT FK_ACTIVITY_COMPANY FOREIGN KEY(COMPANY_COD) REFERENCES ACTIVITY(COMPANY_COD),
    CONSTRAINT FK_ACTIVITY_DRIVER FOREIGN KEY(DRIVER_DNI) REFERENCES DRIVER(DRIVER_DNI)
); 