CREATE TABLE DRIVER_WORK (
    COD_COMPANY NUMBER(4),
    DRIVER_DNI NUMBER(8),
    WORK_START_DATE DATE,
    WORK_FINISH_DATE DATE NOT NULL,
    CONSTRAINT PK_DRIVER_WORK PRIMARY KEY(COD_COMPANY,DNI,WORK_START_DATE),
    CONSTRAINT FK_DRIVERWORK_COMPANY FOREIGN KEY(COD_COMPANY) REFERENCES COMPANY(COD_COMPANY),
    CONSTRAINT FK_DRIVERWORK_DRIVER FOREIGN KEY(DRIVER_DNI) REFERENCES DRIVER(DNI)
);