CREATE TABLE DRIVER (
    DNI NUMBER(8),
    DRIVER_NAME VARCHAR2(20) NOT NULL,
    FIRST_SURNAME VARCHAR2(15) NOT NULL,
    LAST_SURNAME VARCHAR2(15),
    PREFERRED_IDIOME VARCHAR2(2) NOT NULL,
    DISCHARGE_DATE DATE NOT NULL,
    PLACES_REGION VARCHAR2(20),
    CONSTRAINT PK_DRIVER PRIMARY KEY(DNI),
    CONSTRAINT FK_DRIVER_PLACES FOREIGN KEY(PLACES_REGION) REFERENCES PLACES (REGION)
);
